name: Build and push Docker images

on:
  push:
    branches:
      - main

jobs:
  env:
    registry:
  docker:
    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: ${{env.REGISTRY}}/backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: ${{env.REGISTRY}}/frontend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Copy compose to vps
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          port: ${{secrets.SSH_PORT}}
          source: "docker-compose.yml"
          target: "/home/admin/app"

      - name: Pull on vps
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: admin
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/admin/app
            docker compose pull
            docker compose -f docker-compose.yml -f docker-compose-prod.yml up -d
